### ISSUE TITLE
java.lang.ClassCastException

### ISSUE THREAD

**Issue by umesh0492** [icerockdev/moko-media#72]
```
coroutineScope.launch {
                            //var image: ImageBitmap? by remember { mutableStateOf(null) }
                            val result = picker.pickImage(MediaSource.CAMERA)
                            try {
                                result.toImageBitmap()
                            } catch (e: Exception) {

                            }
                        }
```

```
java.lang.ClassCastException: dev.icerock.moko.media.picker.MediaPickerFragment cannot be cast to dev.icerock.moko.media.picker.ImagePickerFragment
                                                                                                    	at dev.icerock.moko.media.picker.MediaPickerControllerImpl.pickImage(MediaPickerControllerImpl.kt:62)
                                                                                                    	at dev.icerock.moko.media.picker.MediaPickerControllerImpl.pickImage(MediaPickerControllerImpl.kt:44)
```

**Comment by umesh0492** [comment]
With 
dev.icerock.moko:media:0.11.0
dev.icerock.moko:media-compose:0.11.0

**Comment by davgdafa** [comment]
I think you need to all permissions for all versions in the AndroidManifest of the Android app as [in here](https://developer.android.com/about/versions/14/changes/partial-photo-video-access):
```

    <!-- Devices running Android 12L (API level 32) or lower  -->
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" android:maxSdkVersion="32" />

    <!-- Devices running Android 13 (API level 33) or higher -->
    <uses-permission android:name="android.permission.READ_MEDIA_IMAGES"  />
    <uses-permission android:name="android.permission.READ_MEDIA_VIDEO" />

    <!-- To handle the reselection within the app on Android 14 (API level 34) -->
    <uses-permission android:name="android.permission.READ_MEDIA_VISUAL_USER_SELECTED" />
```

**Comment by anton-veretenenko** [comment]
got that exception too, code to reproduce
```
picker.pickImage(MediaSource.CAMERA)
picker.pickMedia()
```

so exception happens when you try to use several pickers from the same composable, because pickerFragmentTag is always the same
