### ISSUE TITLE
OutOfMemoryError for MediaPickerController

### ISSUE THREAD

**Issue by Tetraquark** [icerockdev/moko-media#8]
Got `OutOfMemoryError` for `MediaPickerController`:

```
java.lang.OutOfMemoryError: Failed to allocate a 159694860 byte allocation with 4193664 free bytes and 111MB until OOM
        at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
        at android.graphics.BitmapFactory.nativeDecodeStream(Native Method)
        at android.graphics.BitmapFactory.decodeStreamInternal(BitmapFactory.java:677)
        at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:653)
        at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:691)
        at dev.icerock.moko.media.picker.MediaPickerController$PickerFragment.processGalleryResult(MediaPickerController.kt:226)
        at dev.icerock.moko.media.picker.MediaPickerController$PickerFragment.onActivityResult(MediaPickerController.kt:202)
```

**Comment by Alex009** [comment]
merged
